[package]
name = "grepr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.7"
clap = "4.4.13"
regex = "1.10.2"
walkdir = "2.4.0"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
rand = "0.8.5"
sys-info = "0.9.1"
