[package]
name = "calr"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.79"
chrono = "0.4.31"
clap = "4.4.14"
itertools = "0.12.0"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
