[package]
name = "calr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.7"
clap = "4.4.14"
chrono = "0.4.31"
itertools = "0.12.0"
ansi_term = "0.12.1"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
