[package]
name = "calr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.14"
chrono = "0.4.31"
itertools = "0.10"
ansi_term = "0.12"
anyhow = "1"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
