[package]
name = "uniqr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.14"
anyhow = "1.0.7"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
tempfile = "3.9.0"
rand = "0.8.5"
