[package]
name = "lsr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.7"
chrono = "0.4.31"
clap = "4.4.14"
users = "0.11.0"
tabular = "0.2.0"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
rand = "0.8.5"
