[package]
name = "tailr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.7"
clap = "4.4.14"
num = "0.4.1"
regex = "1.10.2"
once_cell = "1.19.0"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
rand = "0.8.5"
